<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Thank you, John</name>
   <tag></tag>
   <elementGuidId>66ee19fa-f5cc-4d4f-aede-37ed343c4cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#article-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='article-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;thank-you-header&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a772c159-2b2e-4b0c-8768-c0d52703cba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>article-header</value>
      <webElementGuid>5bd8f255-5221-48b5-a525-6ce0f6784068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>thank-you-header</value>
      <webElementGuid>a8a40f73-2dcd-44e3-a96d-75056b655408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you, John!</value>
      <webElementGuid>3de5dbf1-91a5-47fe-909b-2b8ab62c7c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-header&quot;)</value>
      <webElementGuid>b90bba53-ff95-4c45-9c22-ccea310af385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='article-header']</value>
      <webElementGuid>9d56f045-0516-4a13-b7e9-aa2543f8c7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='devexpress.github.io/testcafe'])[1]/preceding::h1[1]</value>
      <webElementGuid>d41a937b-0ea0-46fa-9247-eb12affb17bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you, John!']/parent::*</value>
      <webElementGuid>126ec121-4c84-40e8-bc2a-1ce8e80742fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a4a31405-651f-471c-936e-37e732e9ed79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'article-header' and (text() = 'Thank you, John!' or . = 'Thank you, John!')]</value>
      <webElementGuid>2773d3e0-0991-4d28-9b8d-46be961c8052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
