<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your name_populate</name>
   <tag></tag>
   <elementGuidId>b2a4150c-92e8-4c2d-9a3a-a2b288d12914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#populate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='populate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;populate-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>985ad15c-7463-4945-b03d-170207e4e45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b381486-5064-4550-87ad-67adcdb283c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>populate</value>
      <webElementGuid>07bb7a64-f8f3-47db-ae2f-d6479c195338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>populate-button</value>
      <webElementGuid>e7959e55-a495-4c34-9497-e53035830111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Populate</value>
      <webElementGuid>8a8f4ec7-62b2-4d2f-b0f3-da470efdc7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;populate&quot;)</value>
      <webElementGuid>bf672c83-f3bf-4589-b6c7-ab95509e31c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='populate']</value>
      <webElementGuid>2cd463cd-9b6a-4208-8031-bbaf6efe232b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main-form']/div/div/div/fieldset/input[2]</value>
      <webElementGuid>5002b79c-0939-4c23-afb9-34f5d1a172a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>f176f7f5-dde6-4354-b079-092b02c15cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'populate']</value>
      <webElementGuid>f0980817-7474-42cf-af84-f6c8bd1d392d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
