<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Easy embedding into a Continuous inte_a0aaa1</name>
   <tag></tag>
   <elementGuidId>89a7458d-77b0-40a1-9d68-ca02dd04a738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continuous-integration-embedding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='continuous-integration-embedding']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;ci-checkbox&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f071f2f7-3c3e-481a-943c-39d5847adafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bdbd64a8-d52d-4081-82a8-e27186ccffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CI</value>
      <webElementGuid>f3abab7e-1d85-4ce8-9f53-531e9b12034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continuous-integration-embedding</value>
      <webElementGuid>3685ecb4-1da9-423d-a148-61481c23d65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ci-checkbox</value>
      <webElementGuid>954d3080-341b-46ba-a140-613989601f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continuous-integration-embedding&quot;)</value>
      <webElementGuid>88c96a53-0543-4941-9744-9df0771ea795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='continuous-integration-embedding']</value>
      <webElementGuid>2db0034b-1d56-4126-99c5-4273e3d4e9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main-form']/div/div/div/fieldset[2]/p[4]/label/input</value>
      <webElementGuid>a0d44cbe-b9b7-42e2-97b3-267b33495e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/label/input</value>
      <webElementGuid>4f44f60c-b43e-4066-9cdd-5371690330db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'CI' and @id = 'continuous-integration-embedding']</value>
      <webElementGuid>7167063c-881a-47c9-bdcd-84129cf79df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
