<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Windows_os</name>
   <tag></tag>
   <elementGuidId>b03c3eef-45b3-428b-846d-154540d6b005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#windows</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='windows']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;windows-radio&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73d7c377-d9b4-484d-a0e4-a2cc8c8bc433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4327a8b3-cead-431b-bb1e-ffcc6517a46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>os</value>
      <webElementGuid>816b291a-6e4a-4b51-89f2-dcac0fddaff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>windows</value>
      <webElementGuid>e60fdae4-5c63-4dd5-9a40-45b608c6d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Windows</value>
      <webElementGuid>56933811-acc3-4249-b0f6-835046f5ef60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>windows-radio</value>
      <webElementGuid>5496c7f2-f3ed-43d0-bd18-0c72b890c8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;windows&quot;)</value>
      <webElementGuid>ed2f20c2-a73b-4e9e-94a4-e5f1a2eeb895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='windows']</value>
      <webElementGuid>2ce6e8c9-d411-4a1f-be89-5c13ffd92d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main-form']/div/div/div[2]/fieldset/p/label/input</value>
      <webElementGuid>62092865-e0b0-4f92-acd9-894d8a58d157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/p/label/input</value>
      <webElementGuid>0924f90a-ed0e-49d1-bc36-32421623d035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'os' and @id = 'windows']</value>
      <webElementGuid>a7dd2939-4225-4085-afa8-f99aae7f25c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
