<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your name_name</name>
   <tag></tag>
   <elementGuidId>43df40d1-24fc-4f23-9d15-91f3a2542ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#developer-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='developer-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;name-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afd7583e-b8af-46a5-93d0-a808d83ecb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>developer-name</value>
      <webElementGuid>16177d5a-a99d-4931-b6e9-14743c92aebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>c8e6c56a-dc8d-40b4-9031-e24510aaf027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e61e64a-eda2-4d87-bb96-462c941360ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>name-input</value>
      <webElementGuid>142f3ac3-e865-4d13-9997-3cfea679bd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;developer-name&quot;)</value>
      <webElementGuid>316dd40a-1026-4caa-9995-efd8e3890901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='developer-name']</value>
      <webElementGuid>919882df-9a1d-439a-a3b3-0af1f5d1854e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main-form']/div/div/div/fieldset/input</value>
      <webElementGuid>a0bcfb8a-7fad-4508-9db3-5129b42c82c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c0a4f17a-db4c-46c4-978a-b65901060fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'developer-name' and @name = 'name' and @type = 'text']</value>
      <webElementGuid>7ab53498-d849-4e21-b34f-fcfab9dafc71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
